"""Offline retrieval engine used by the HURC1 Copilot fallback.

The module intentionally depends only on Python's standard library so it can run
inside the existing Next.js server action without installing an ML stack. It
implements a small hybrid lexical retriever (BM25 + phrase/category bonuses),
loads versioned ingestion indexes when available, and preserves the historical
JSON response contract consumed by ``askCopilot``.
"""

from __future__ import annotations

import glob
import hashlib
import json
import math
import os
import re
import sys
import unicodedata
from collections import Counter
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Mapping, Sequence

ENGINE_NAME = "Hybrid BM25 Offline RAG v3"
MAX_QUERY_CHARS = 4_000
MAX_ANSWER_CHARS = 3_500
DEFAULT_TOP_K = 3
DEFAULT_MIN_CONFIDENCE = 0.32

# Safe last-resort content. Production deployments should point
# RAG_KNOWLEDGE_PATH to an index generated by document_ingestion_v2.py.
FALLBACK_MANUAL_PAGES: list[dict[str, Any]] = [
    {
        "id": "doc_1",
        "text": (
            "Mã lỗi E-404 trên động cơ kéo (Traction Motor) biểu thị tình trạng "
            "quá nhiệt stator. Cách khắc phục: dừng tàu theo quy trình an toàn, "
            "kiểm tra quạt làm mát và vệ sinh bộ lọc bụi."
        ),
        "category": "Motor",
        "document_code": "DEMO-MOTOR-001",
    },
    {
        "id": "doc_2",
        "text": (
            "Bảo dưỡng định kỳ hộp số (Gearbox) mức 2: thay dầu bôi trơn sau mỗi "
            "50.000 km, kiểm tra độ rơ bánh răng và độ rung theo giới hạn của tài liệu bảo trì."
        ),
        "category": "Gearbox",
        "document_code": "DEMO-GEARBOX-001",
    },
    {
        "id": "doc_3",
        "text": (
            "Hệ thống phanh báo đèn đỏ có thể liên quan đến áp suất khí nén hoặc "
            "rò rỉ. Cần cô lập thiết bị theo quy trình, kiểm tra cảm biến, van một chiều và BCU."
        ),
        "category": "Brake",
        "document_code": "DEMO-BRAKE-001",
    },
    {
        "id": "doc_4",
        "text": (
            "Khi thay vòng bi, sử dụng dụng cụ chuyên dùng và kích thủy lực. "
            "Không dùng búa đập trực tiếp vào vòng ngoài của vòng bi."
        ),
        "category": "Wheel",
        "document_code": "DEMO-WHEEL-001",
    },
]

BASE_STOPWORDS = {
    "a", "an", "and", "are", "as", "at", "be", "by", "for", "from", "how", "in",
    "is", "it", "of", "on", "or", "that", "the", "this", "to", "what", "when", "where",
    "which", "with", "và", "là", "của", "cho", "trong", "trên", "dưới", "với", "một",
    "các", "những", "này", "đó", "được", "bị", "có", "không", "như", "khi", "tại",
    "về", "theo", "từ", "đến", "hãy", "giúp", "tôi", "cần", "nào", "gì", "sao",
}

WORD_RE = re.compile(r"[^\W_]+(?:[-./][^\W_]+)*", re.UNICODE)


def normalize_text(text: str, *, fold_accents: bool = False) -> str:
    normalized = unicodedata.normalize("NFKC", str(text or "")).lower().strip()
    normalized = re.sub(r"\s+", " ", normalized)
    if fold_accents:
        decomposed = unicodedata.normalize("NFD", normalized.replace("đ", "d"))
        normalized = "".join(ch for ch in decomposed if unicodedata.category(ch) != "Mn")
    return normalized


FOLDED_STOPWORDS = {normalize_text(word, fold_accents=True) for word in BASE_STOPWORDS}


def tokenize(text: str) -> list[str]:
    """Return Unicode-aware, accent-insensitive terms without double counting."""
    folded = normalize_text(text, fold_accents=True)
    terms: list[str] = []
    for token in WORD_RE.findall(folded):
        token = token.strip("-./")
        if len(token) < 2 or token in FOLDED_STOPWORDS:
            continue
        terms.append(token)
    return terms


def _stable_id(content: str) -> str:
    return hashlib.sha256(content.encode("utf-8")).hexdigest()[:20]


@dataclass(frozen=True)
class Document:
    id: str
    text: str
    metadata: dict[str, Any]

    @property
    def category(self) -> str:
        return str(
            self.metadata.get("related_system")
            or self.metadata.get("category")
            or self.metadata.get("system")
            or "General"
        )

    @property
    def document_code(self) -> str:
        return str(self.metadata.get("document_code") or self.metadata.get("code") or self.id)


def _coerce_document(raw: Mapping[str, Any], position: int) -> Document | None:
    text = str(raw.get("content") or raw.get("text") or "").strip()
    if not text:
        return None

    metadata = dict(raw.get("metadata") or {})
    for key in (
        "document_code", "code", "category", "related_system", "system", "title",
        "version", "issue_date", "contractor", "related_asset", "source_file", "page",
        "section", "chunk_index", "content_hash",
    ):
        if key in raw and key not in metadata:
            metadata[key] = raw[key]

    doc_id = str(raw.get("id") or metadata.get("chunk_id") or _stable_id(f"{position}:{text}"))
    return Document(id=doc_id, text=text, metadata=metadata)


def _extract_records(payload: Any) -> list[Mapping[str, Any]]:
    if isinstance(payload, list):
        return [item for item in payload if isinstance(item, Mapping)]
    if not isinstance(payload, Mapping):
        return []

    for key in ("chunks", "documents", "records"):
        value = payload.get(key)
        if isinstance(value, list):
            return [item for item in value if isinstance(item, Mapping)]
    return []


def _candidate_index_paths() -> list[Path]:
    candidates: list[Path] = []
    env_path = os.getenv("RAG_KNOWLEDGE_PATH", "").strip()
    if env_path:
        candidates.append(Path(env_path))

    project_root = Path(__file__).resolve().parents[3]
    index_dir = project_root / "data" / "vector_db"
    candidates.extend(
        [
            index_dir / "latest.json",
            index_dir / "current_index.json",
        ]
    )

    versioned = sorted(
        (
            Path(path)
            for pattern in ("metro_rag_index_v3_*.json", "metro_rag_index_v2_*.json")
            for path in glob.glob(str(index_dir / pattern))
        ),
        key=lambda path: path.stat().st_mtime if path.exists() else 0,
        reverse=True,
    )
    candidates.extend(versioned)
    return candidates


def _resolve_latest_pointer(path: Path, payload: Any) -> tuple[Path, Any]:
    if path.name != "latest.json" or not isinstance(payload, Mapping):
        return path, payload
    target = payload.get("path") or payload.get("index_path") or payload.get("filename")
    if not target:
        return path, payload
    target_path = Path(str(target))
    if not target_path.is_absolute():
        target_path = path.parent / target_path
    with target_path.open("r", encoding="utf-8") as handle:
        return target_path, json.load(handle)


def load_documents(path: str | os.PathLike[str] | None = None) -> tuple[list[Document], str]:
    paths = [Path(path)] if path else _candidate_index_paths()
    for candidate in paths:
        if not candidate.exists() or not candidate.is_file():
            continue
        try:
            with candidate.open("r", encoding="utf-8") as handle:
                payload = json.load(handle)
            resolved_path, payload = _resolve_latest_pointer(candidate, payload)
            records = _extract_records(payload)
            documents = [doc for i, raw in enumerate(records) if (doc := _coerce_document(raw, i))]
            if documents:
                return documents, str(resolved_path)
        except (OSError, ValueError, TypeError):
            continue

    fallback_docs = [
        doc for i, raw in enumerate(FALLBACK_MANUAL_PAGES) if (doc := _coerce_document(raw, i))
    ]
    return fallback_docs, "embedded-demo-fallback"


@dataclass(frozen=True)
class SearchHit:
    document: Document
    raw_score: float
    confidence: float
    matched_terms: tuple[str, ...]


def _char_trigrams(text: str) -> set[str]:
    compact = re.sub(r"\s+", " ", normalize_text(text, fold_accents=True))
    if len(compact) < 3:
        return {compact} if compact else set()
    return {compact[i:i + 3] for i in range(len(compact) - 2)}


def hybrid_search(
    query: str,
    docs: Sequence[Document],
    *,
    top_k: int = DEFAULT_TOP_K,
    category: str | None = None,
) -> list[SearchHit]:
    query_terms = tokenize(query)
    if not query_terms or not docs:
        return []

    filtered_docs = [
        doc
        for doc in docs
        if not category
        or normalize_text(doc.category, fold_accents=True)
        == normalize_text(category, fold_accents=True)
    ]
    if not filtered_docs:
        return []

    searchable_texts = [
        " ".join(
            part
            for part in (
                str(doc.metadata.get("title") or ""),
                doc.document_code,
                doc.category,
                doc.text,
            )
            if part
        )
        for doc in filtered_docs
    ]
    tokenized_docs = [tokenize(text) for text in searchable_texts]
    doc_term_counts = [Counter(tokens) for tokens in tokenized_docs]
    avg_doc_len = sum(max(1, len(tokens)) for tokens in tokenized_docs) / len(tokenized_docs)

    document_frequency: Counter[str] = Counter()
    for counts in doc_term_counts:
        document_frequency.update(counts.keys())

    normalized_query = normalize_text(query, fold_accents=True)
    query_trigrams = _char_trigrams(query)
    query_term_set = set(query_terms)
    total_docs = len(filtered_docs)
    hits: list[SearchHit] = []

    for doc, searchable_text, counts, tokens in zip(
        filtered_docs, searchable_texts, doc_term_counts, tokenized_docs
    ):
        doc_len = max(1, len(tokens))
        score = 0.0
        matched: set[str] = set()

        for term in query_term_set:
            tf = counts.get(term, 0)
            if not tf:
                continue
            matched.add(term)
            df = document_frequency.get(term, 0)
            idf = math.log(1 + (total_docs - df + 0.5) / (df + 0.5))
            denominator = tf + 1.5 * (1 - 0.75 + 0.75 * doc_len / avg_doc_len)
            score += idf * (tf * 2.5) / denominator

        folded_doc = normalize_text(searchable_text, fold_accents=True)
        folded_code = normalize_text(doc.document_code, fold_accents=True)
        folded_category = normalize_text(doc.category, fold_accents=True)

        if len(normalized_query) >= 5 and normalized_query in folded_doc:
            score += 1.25
        if folded_code and folded_code in normalized_query:
            score += 1.0
        if folded_category and folded_category in normalized_query:
            score += 0.65

        doc_trigrams = _char_trigrams(searchable_text[:2_000])
        if query_trigrams and doc_trigrams:
            trigram_similarity = len(query_trigrams & doc_trigrams) / max(1, len(query_trigrams))
            score += 0.8 * trigram_similarity

        coverage = len(matched) / max(1, len(query_term_set))
        score += 0.9 * coverage

        # Confidence is bounded and interpretable; it is not a probability.
        confidence = (1 - math.exp(-score / 3.2)) * (0.65 + 0.35 * coverage)
        confidence *= coverage**0.7
        confidence = max(0.0, min(1.0, confidence))
        if score > 0:
            hits.append(
                SearchHit(
                    document=doc,
                    raw_score=round(score, 6),
                    confidence=round(confidence, 4),
                    matched_terms=tuple(sorted(matched)),
                )
            )

    hits.sort(key=lambda hit: (hit.confidence, hit.raw_score), reverse=True)
    return hits[: max(1, min(int(top_k), 10))]


def _clean_excerpt(text: str, limit: int = 900) -> str:
    excerpt = re.sub(r"\s+", " ", text).strip()
    if len(excerpt) <= limit:
        return excerpt
    return excerpt[: limit - 1].rstrip() + "…"


def build_answer(hits: Sequence[SearchHit]) -> str:
    if not hits:
        return "Xin lỗi, tôi không tìm thấy thông tin phù hợp trong kho tài liệu kỹ thuật."

    lines = ["Theo các tài liệu kỹ thuật phù hợp nhất:"]
    for index, hit in enumerate(hits, start=1):
        label = hit.document.document_code
        category = hit.document.category
        lines.append(f"{index}. [{label} | {category}] {_clean_excerpt(hit.document.text)}")
    return "\n".join(lines)[:MAX_ANSWER_CHARS]


def answer_query(
    query: str,
    *,
    top_k: int = DEFAULT_TOP_K,
    category: str | None = None,
    min_confidence: float = DEFAULT_MIN_CONFIDENCE,
    knowledge_path: str | None = None,
) -> dict[str, Any]:
    clean_query = str(query or "").strip()
    if not clean_query:
        raise ValueError("Query is required")
    if len(clean_query) > MAX_QUERY_CHARS:
        raise ValueError(f"Query exceeds {MAX_QUERY_CHARS} characters")

    documents, knowledge_source = load_documents(knowledge_path)
    hits = hybrid_search(clean_query, documents, top_k=top_k, category=category)
    if hits:
        relative_floor = max(min_confidence, hits[0].confidence * 0.55)
        accepted_hits = [hit for hit in hits if hit.confidence >= relative_floor]
    else:
        accepted_hits = []

    if not accepted_hits:
        return {
            "answer": "Xin lỗi, tôi không tìm thấy thông tin đủ tin cậy trong kho tài liệu kỹ thuật.",
            "confidence": 0.0,
            "engine": ENGINE_NAME,
            "knowledge_source": knowledge_source,
            "sources": [],
        }

    top_confidence = accepted_hits[0].confidence
    return {
        "answer": build_answer(accepted_hits),
        "confidence": top_confidence,
        "engine": ENGINE_NAME,
        "knowledge_source": knowledge_source,
        "sources": [
            {
                "id": hit.document.id,
                "document_code": hit.document.document_code,
                "category": hit.document.category,
                "score": hit.raw_score,
                "confidence": hit.confidence,
                "matched_terms": list(hit.matched_terms),
                "metadata": hit.document.metadata,
            }
            for hit in accepted_hits
        ],
    }


def _read_cli_payload(argv: Sequence[str]) -> Mapping[str, Any]:
    if len(argv) <= 1:
        raise ValueError("No query provided")
    payload = json.loads(argv[1])
    if not isinstance(payload, Mapping):
        raise ValueError("Input must be a JSON object")
    return payload


def main(argv: Sequence[str] | None = None) -> int:
    argv = argv or sys.argv
    try:
        payload = _read_cli_payload(argv)
        result = answer_query(
            str(payload.get("query", "")),
            top_k=int(payload.get("top_k", DEFAULT_TOP_K)),
            category=str(payload["category"]) if payload.get("category") else None,
            min_confidence=float(payload.get("min_confidence", DEFAULT_MIN_CONFIDENCE)),
            knowledge_path=str(payload["knowledge_path"]) if payload.get("knowledge_path") else None,
        )
        print(json.dumps(result, ensure_ascii=False))
        return 0
    except (ValueError, TypeError, json.JSONDecodeError) as exc:
        print(json.dumps({"error": str(exc), "engine": ENGINE_NAME}, ensure_ascii=False))
        return 2
    except Exception:
        # Keep server output deterministic and avoid exposing filesystem or stack details.
        print(json.dumps({"error": "Offline RAG engine failed", "engine": ENGINE_NAME}, ensure_ascii=False))
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
